IDEAS = {'tacos': ['ground beef', 'lettuce', 'tortillas', 'taco shells', 'cheese', 'tomatoes', 'taco seasoning'],
         'meatloaf': ['ground beef', ],
         'burgers': ['ground beef or hamburger patties', 'lettuce', 'cheese', 'tomatoes', 'fries', 'condiments'],
         'biscuits and gravy': ['sausage', 'biscuits', 'country gravy'],
         'lasagna': ['ground beef', 'lasagna noodles', 'spaghetti sauce', 'cheese'],
         'hamburger helper': ['hamburger helper', 'ground beef'],
         'steak and eggs': ['steak', 'eggs'],
         'pizza': ['pizza'],
         'wings': ['chicken wings', 'wings sauce'],
         'salad': ['lettuce', 'cheese', 'salad dressing', 'bacon bits', 'tomatoes', 'cucumbers', 'jalapenos'],
         'chicken alfredo': ['chicken', 'alfredo sauce', 'noddles', 'Parmesan cheese'],
         'enchiladas': ['beef or chicken', 'cheese', 'corn tortillas', 'enchilada sauce', 'jalapenos'],
         'barbeque meat cups': ['ground beef', 'cheese', 'barbeque sauce', 'biscuit dough'],
         'fish sticks and fries': ['fish sticks', 'fries'],
         'chicken nuggets': ['chicken nuggets', ' a vegetable'],
         'hot dogs': ['hot dogs'],
         'mac and cheese with pigs-in-a-blanket': []
         }
